### ISSUE TITLE
Describe blockers for getting users on Mattermoz

### ISSUE THREAD

**Issue by alanmoo** [mozilla/mattermoz#5]
_Work in progress_
- [ ] Direct people to mobile apps #14 
- [ ] Get push notifications working for mobile apps #24 
- [x] Email notifications/verification (#15)

**Comment by alanmoo** [comment]
This is covered by other issues now
