### ISSUE TITLE
Design MoFo Onboarding

### ISSUE THREAD

**Issue by simonwex** [mozilla/mattermoz#67]
Design MoFo Onboarding

**Comment by xmatthewx** [comment]
## Design and refine on-boarding experience

Goal: make the initial experience more friendly and coherent, and remove the biggest points of confusion and pain. 

Scope: Focus on the easy improvements we can land in the short-term, that fall outside of the platform itself (like the invitation email).

#### Why?
- The success of the platform will hinge in part on a smooth on-boarding experience, for both individuals and for groups. 
- A good experience will help people feel welcomed and give various channels the critical mass needed for lively interesting conversation. 
- Lastly, on-boarding will help people make the leap from other ways they can communicate to avoid a fragmented experience 

#### How?

Consider things such as...
- [ ] email invite ([version 1](https://github.com/MozillaFoundation/plan/issues/712#issuecomment-182520728))
- [ ] signup
- [ ] help/faq/[user guide](https://github.com/mozilla/chat.mozillafoundation.org/wiki/User-Guide)
- [ ] [native app install](https://github.com/mozilla/chat.mozillafoundation.org/issues/67#issuecomment-198092141) 
  - ([Mattermost download page](https://github.com/mattermost/desktop/releases)) 
  - (Mozilla shortlink to download) 
- [ ] notification configs
- [ ] participation/community guidelines #65

**Comment by xmatthewx** [comment]
<img width="402" alt="screenshot 2016-03-17 14 52 27" src="https://cloud.githubusercontent.com/assets/53411/13859865/ff1eafee-ec5b-11e5-9061-f88e98761f19.png">

It could be interesting to create a welcome bot that sends tips during the first few days of use.

**Comment by xmatthewx** [comment]
# Native App
- Installing the native app comes with some challenges. 
- Until this is packaged by an Apple recognized developer, we'll need some serious user support.  

## OS X

WIP instructions:
1. download [link] and open folder 
1. drag to applications
 <img width="974" alt="screenshot 2016-03-17 17 24 23" src="https://cloud.githubusercontent.com/assets/53411/13861741/6f46a6ce-ec65-11e5-9201-c6b0034f6a9a.png">
1. open application
1. don't worry about scary warning
1. open system preferences > security and privacy
1. click open anyway 
<img width="1075" alt="screenshot 2016-03-15 17 19 01" src="https://cloud.githubusercontent.com/assets/53411/13861807/bb445256-ec65-11e5-89a2-6a3a90e09af7.png">
1. open the application again (Is this Windows Vista?)
1. click open
<img width="806" alt="screenshot 2016-03-15 17 19 35" src="https://cloud.githubusercontent.com/assets/53411/13861597/86772432-ec64-11e5-839c-117d2bb29461.png">
1. Enter Mozilla and URL
<img width="952" alt="screenshot 2016-03-15 17 51 00" src="https://cloud.githubusercontent.com/assets/53411/13861602/8d5fa968-ec64-11e5-826a-d5b963d450e3.png">

**Comment by kristinashu** [comment]
For reference, this site has a bunch of first-time UX teardowns http://www.useronboard.com/onboarding-teardowns/ including one for slack http://www.useronboard.com/how-slack-onboards-new-users/

**Comment by xmatthewx** [comment]
Thanks @kristinashu - I edited my first comment in this thread for more context. It'd be good to dig up some community building best practices to inform this work.

**Comment by xmatthewx** [comment]
@alanmoo - when do y'all plan to invite the next round of users?

**Comment by simonwex** [comment]
@xmatthewx I've got to get caught up and push this over the line with @alanmoo. Last week was all-consuming

**Comment by kristinashu** [comment]
Few initial thoughts for the onboarding email:

We should think of the invite email as the landing page of a site and really focus on the value proposition and benefits of using Chat and less on the nitty gritty details of signing up and installing.

For the value prop, we should focus less on the how it's a slack or irc alternative but more on why those exist in the first place.
- better communication all in one spot
- fewer emails and meetings
- open and inclusive

Then we can get into the features with a few screen caps:
https://www.irccloud.com/
https://slack.com/is
http://www.mattermost.org/features/

Messaging & Files
- Send messages and comments across public, private and 1-1 channels
- Personalize notifications
- Share files and images

Archiving & Search
- Search channels for past messages and comments
- View recent mentions of your name, username, nickname, and custom search terms
- Receive messages even if you're offline

To reinforce that Chat is friendly and accessible, we should add some illustrations or photos to the email to make it less intimidating.

Details like installing the desktop app and the recent mentions feature can be featured in later emails once people are comfortable with the basics.

I'm also wondering if getting Chat into the app store is a possibility so we can avoid the crazy work around currently needed on Macs?

**Comment by alanmoo** [comment]
Hmm, thought I responded to this.

Not sure why @xmatthewx encountered the issue with an unsigned package, I haven't had that and my settings look the same as his.

As for the onboarding, the idea of it as a type of landing page is interesting- maybe as a sort of intermediate page greeting people on first visit? We could write an email explaining it all, but who reads long emails? (And I don't really want to code an HTML email...)

I totally agree with the rest of your points, @kristinashu - we're inviting a technically competent audience, so we should focus more on the "why" than the "how".

**Comment by alanmoo** [comment]
@simonwex didn't you have a bulleted list of "why we're using this" at some point?

**Comment by xmatthewx** [comment]
- [ ] When we sign and package the app, can we change the title? From `electron-mattermost` to `Mozilla Chat`?

**Comment by alanmoo** [comment]
It's now called "Mattermost" by default when you download it, though I imagine that's something we could do.
